version: "3"
services:
  database:
    image: mysql:8.0.27
    container_name: mysql_container
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "study_with_me"
