spring:
  config:
    activate:
      on-profile: dev
    import:
      - security/application.yml
      - security/application-dev-datasource.yml
      - application-logging.yml
      - application-mapping.yml
