spring:
  config:
    activate:
      on-profile: prod
    import:
      - security/application-external.yml
      - security/application-prod-datasource.yml
      - application-logging.yml
      - application-mapping.yml
