name: Backend CI

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository를 가져옵니다
        uses: actions/checkout@v3

      - name: JDK 17을 설치합니다
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Timezone을 Asia/Seoul로 설정합니다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      - name: Gradle을 이용해서 프로젝트 빌드를 수행합니다
        run: ./gradlew clean build

      - name: 테스트 결과를 등록합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
