name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Backend Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Repository를 가져온다
        uses: actions/checkout@v3

      - name: JDK 17을 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Timezone을 Asia/Seoul로 설정한다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Github Action Screts로부터 application-prod.yml을 가져온다
        env:
          PROD_YML: ${{ secrets.PROD_YML }}
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "$PROD_YML" | base64 --decode > ./application-prod.yml
        shell: bash

      - name: Gradle 명령 실행을 위한 권한을 부여한다
        run: chmod +x gradlew

      - name: Gradle build를 수행한다
        run: ./gradlew bootJar

      - name: NCP Server로 빌드 파일을 전송한다
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          source: "./build/libs/StudyWithMe.jar, ./script/deploy.sh"
          target: "/app"

      - name: NCP Server에 SSH 접속 후 deploy.sh을 실행시킨다
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /app/script
            sudo chmod +x deploy.sh
            sudo ./deploy.sh
